# Generated by Django 5.1.6 on 2025-02-13 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(default='default.jpg', upload_to='user_profile')),
                ('user_bio', models.TextField(default='A passionate and result-driven software developer with...')),
                ('user_education', models.CharField(default='ABC Institute Of Technology', max_length=200)),
                ('user_cgpa', models.DecimalField(decimal_places=2, default=7.65, max_digits=4)),
                ('work_experience', models.CharField(default='1 year of experience in software development', max_length=200)),
                ('user_resume', models.FileField(default='default_resume.pdf', upload_to='user_resume')),
                ('user_location', models.CharField(default='State/City', max_length=200)),
                ('user_skills', models.CharField(blank=True, default='', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
