# Generated by Django 5.1.6 on 2025-02-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_applicantprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='user_skills',
            field=models.CharField(blank=True, default='python,java,react', max_length=500),
        ),
    ]
