# Generated by Django 5.1.6 on 2025-02-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_applicantprofile_user_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='user_image',
            field=models.ImageField(default='default.png', upload_to='user_profile'),
        ),
    ]
