# Generated by Django 5.1.6 on 2025-02-18 13:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_range', models.CharField(choices=[('0-3', '0-3 Lakhs'), ('3-6', '3-6 Lakhs'), ('6-10', '6-10 Lakhs'), ('10-15', '10-15 Lakhs'), ('15-20', '15-20 Lakhs'), ('20+', '20+ Lakhs')], max_length=5)),
                ('work_mode', models.CharField(choices=[('WFO', 'Work from Office'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=10)),
                ('role', models.CharField(max_length=255)),
                ('experience', models.CharField(choices=[('0-1', '0-1 years'), ('1-3', '1-3 years'), ('3-5', '3-5 years'), ('5-7', '5-7 years'), ('7-10', '7-10 years'), ('10+', '10+ years')], max_length=5)),
                ('time_range', models.IntegerField(choices=[(0, 'Freshness'), (1, 'Last 1 Day'), (3, 'Last 3 Days'), (7, 'Last 7 Days'), (15, 'Last 15 Days'), (30, 'Last 30 Days')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
                ('application_deadline', models.DateField(default=django.utils.timezone.now)),
                ('number_of_openings', models.PositiveIntegerField(default=1)),
                ('job_skills', models.CharField(blank=True, default='python,java,react', max_length=500)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='job.employerprofile')),
            ],
        ),
    ]
