# Generated by Django 5.1.6 on 2025-02-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('filled', 'Filled')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='experience',
            field=models.CharField(choices=[('0-1', '0-1 years'), ('1-3', '1-3 years'), ('3-5', '3-5 years'), ('5-7', '5-7 years'), ('7-10', '7-10 years'), ('10+', '10+ years')], default='0-1', max_length=5),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salary_range',
            field=models.CharField(choices=[('0-3', '0-3 Lakhs'), ('3-6', '3-6 Lakhs'), ('6-10', '6-10 Lakhs'), ('10-15', '10-15 Lakhs'), ('15-20', '15-20 Lakhs'), ('20+', '20+ Lakhs')], default='0-3', max_length=5),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='time_range',
            field=models.IntegerField(choices=[(0, 'Freshness'), (1, 'Last 1 Day'), (3, 'Last 3 Days'), (7, 'Last 7 Days'), (15, 'Last 15 Days'), (30, 'Last 30 Days')], default=0),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='work_mode',
            field=models.CharField(choices=[('WFO', 'Work from Office'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], default='WFO', max_length=10),
        ),
    ]
