# Generated by Django 5.1.6 on 2025-02-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_jobs_status_alter_jobs_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='max_salary',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='min_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
