# Generated by Django 5.1.6 on 2025-02-21 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_savejobs'),
        ('users', '0004_alter_applicantprofile_user_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicationSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_application_skills', models.CharField(max_length=200)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job_application_skills',), name='unique_job_skills')],
            },
        ),
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobs')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.applicantprofile')),
                ('JobApplications_skills', models.ManyToManyField(blank=True, related_name='job_applications', to='job.jobapplicationskills')),
            ],
            options={
                'unique_together': {('applicant', 'job')},
            },
        ),
    ]
